config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :restaurants
  resources :customers
  resources :waitlists
  devise_scope :user do
     get "signup-user", to: "users/registrations#new_user"
     get "signup-restaurant", to: "users/registrations#new_rest"
     post "create-user", to: "users/registrations#create_user"
     post "create-restaurant", to: "users/registrations#create_rest"
     delete "destroy-user", to: "users/registrations#destroy"
     get "login", to: "users/sessions#new"
     get "sign_in", to: "users/sessions#new"
     post "sign_in", to: "users/sessions#create", as: "new_sign_in"
     get "logout", to: "users/sessions#destroy"
     get 'setting', to: "users/registrations#edit"
  end
  devise_for :users, controllers: {registrations: "users/registrations"}

  root 'dynamic_pages#home'

  get 'index.html' => 'dynamic_pages#index'
  get 'signup.html' => 'dynamic_pages#signup'
  get 'profile.html' => 'dynamic_pages#profile'
  get 'settings.html' => 'dynamic_pages#settings'
  get 'favorite.html' => 'dynamic_pages#favorite'
  get 'payment.html' => 'dynamic_pages#payment'
  get 'delivery.html' => 'dynamic_pages#delivery'

  get 'index' => 'dynamic_pages#index'
  get 'signup' => 'dynamic_pages#signup'
  get 'profile' => 'dynamic_pages#profile'
  get 'restaurants' => 'restaurants#index'
  get 'settings' => 'dynamic_pages#settings'
  get 'favorite' => 'dynamic_pages#favorite'
  get 'payment' => 'dynamic_pages#payment'
  get 'delivery' => 'dynamic_pages#delivery'
  get 'home' => 'dynamic_pages#home'
  get 'restaurant_page' => 'dynamic_pages#restaurant'

  get 'waitlists_new' => 'waitlists#new'
  post 'waitlists_new' => 'waitlists#create'

  get 'restaurant_new' => 'restaurants#new'
  get 'menus_new' => 'menus#new'
  get 'menus_edit' => 'menus#edit'

end

app/models/waitlist.rb
class Waitlist < ActiveRecord::Base

    validates :people, presence: true
    validates :cust_id, presence: true
    validates :rest_id, presence: true
    belongs_to :customer
    belongs_to :restaurant
    belongs_to :user

    def self.get_restaurant_waitlist(user_id)
        return Waitlist.where(rest_id: user_id).order(:created_at)
    end

    def self.get_customer_waitlist(user_id)
        list_and_position = []
        lists = Waitlist.where(cust_id: user_id).order(:created_at)
        lists.each do |list|
            this_list = get_restaurant_waitlist(list.rest_id)
            pos = this_list.where('created_at < ?', list.created_at).count + 1
            # pos = this_list.count(:conditions => ['created_at < ?', list.created_at])
            list_and_position << {:list => list, :position => pos}
        end
        return list_and_position
    end

    def check_params
        if User.find_by(id: cust_id) == nil || User.find_by(id: rest_id) == nil || !User.find_by(id: rest_id).rest
            errors.add(:rest_id, "Invalid restaurant/customer id")
            return false
        end
        if (cust_id == rest_id) #for restaurant to put on their own waitlist
            return true
        end
        if User.find_by(id: cust_id).rest && (cust_id != rest_id)
            return false
        end
        if Waitlist.where(cust_id: cust_id, rest_id: rest_id).size > 0
            errors.add(:base, "You have waitlisted on this restaurant")
            return false
        end
        return true
    end



end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController
  before_action :set_waitlist, only: [:show, :edit, :update, :destroy]

  # GET /waitlists
  # GET /waitlists.json
  def index

    # @waitlists = Waitlist.all
    if user_signed_in?
      if current_user.rest
        if Restaurant.find_by_user_id(current_user.id) != nil
          @lists = Waitlist.get_restaurant_waitlist(current_user.id)
          render 'rest_index.html.erb' 
        else
          redirect_to restaurant_new_path
        end
      else
        # @lists = Waitlist.where(:cust_id == current_user.id)
        @waitlists = Waitlist.get_customer_waitlist(current_user.id)
        render 'cust_index.html.erb'   
      end
    else
      redirect_to login_path
    end
  end

  # GET /waitlists/1
  # GET /waitlists/1.json
  def show
  end

  # GET /waitlists/new
  def new
    if user_signed_in?
      @waitlist = Waitlist.new
    else
      redirect_to login_path
    end
  end

  # GET /waitlists/1/edit
  def edit
  end

  # POST /waitlists
  # POST /waitlists.json
  def create
    cur_rest = params[:waitlist][:rest_id]
    cur_people = params[:waitlist][:people]
    cur_name = params[:waitlist][:name]
    # render text: params
    waitlist_params = {cust_id: current_user.id, rest_id: cur_rest, people: cur_people, name: cur_name}
    @waitlist = Waitlist.new(waitlist_params)
    if !@waitlist.valid?
      flash[:error] = "Number of People can't be blank"
      redirect_to waitlists_new_path(:rest_id => cur_rest)
      return
    end


    if @waitlist.check_params
      respond_to do |format|
        if @waitlist.save
          flash.now[:notice] = 'Waitlist was successfully created.'
          format.html { redirect_to waitlists_path, notice: 'Waitlist was successfully created.' }
          format.json { render :show, status: :created, location: @waitlist }
        else
          format.html { render :new }
          format.json { render json: @waitlist.errors, status: :unprocessable_entity }
        end

      end
    else 
      flash[:error] = 'You have waitlisted on this restaurant.'
      redirect_to waitlists_path
    end
  end

  # PATCH/PUT /waitlists/1
  # PATCH/PUT /waitlists/1.json
  def update
    respond_to do |format|
      if @waitlist.update(waitlist_params)
        format.html { redirect_to @waitlist, notice: 'Waitlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @waitlist }
      else
        format.html { render :edit }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitlists/1
  # DELETE /waitlists/1.json
  def destroy
    @waitlist.destroy
    respond_to do |format|
      format.html { redirect_to waitlists_path, notice: 'Waitlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitlist
      @waitlist = Waitlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waitlist_params
      params.require(:waitlist).permit(:cust_id, :rest_id, :people, :name)
    end
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/waitlists/_form.html.erb
<%= form_for(@waitlist) do |f| %>
  <% if @waitlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@waitlist.errors.count, "error") %> prohibited this waitlist from being saved:</h2>

      <ul>
      <% @waitlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waitlists/_waitrest.html.erb
<tr>
  <td>
    <% name = Users.find_by(id: @list.cust_id).name %>
    <%= name %>
  </td>
  <td>
    <%= @list.people %>
  </td>
</tr>
<% end -%>

app/views/waitlists/cust_index.html.erb
<body class="profile">
<div class="loading-page"></div>
<main>
  <div class="parallax-container">
      <div class="parallax"><img src="build/img/stock/cover-user.jpg" class="width-full" ></div>
      <div class="text text-center">
        <h1> <%=current_user.name %> </h1>
      </div>
    </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 noPadding">
        <div class="wrapper-left">
          <div class="side-pannel">
            <a href="profile.html" class="tab"><span class="fa fa-home"></span> Home</a>
            <a href="favorite.html" class="tab"><span class="fa fa-star"></span> Favorite</a>
            <a href="/waitlists"class="tab chosen"><span class="fa fa-hourglass"></span> Waitlist</a>
            <a href="delivery.html"class="tab"><span class="fa fa-rocket"></span> Delivery</a>
            <a href="payment.html"class="tab"><span class="fa fa-credit-card"></span>Payment</a>
            <a href="/setting"class="tab"><span class="fa fa-cog"></span>Settings</a>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
        <div class="wrapper-right">
          <div class="header text-center">
            Waitlist
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <% if flash[:error] %>
              <div class="alert alert-danger"><%= flash[:error] %></div>
            <% end %>
          </div>
          <% if not @waitlists.empty? %>
            <% @waitlists.each do |waitlist| %>
                <% list = waitlist[:list] %>
                <% pos = waitlist[:position] %>
                <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                  <a href="#">
                    <div class="box-option">
                      <img src="build/img/stock/restaurant.jpg"/>
                      <div class="text">
                        <% name = User.where(id: list.rest_id).first.name %>
                          
                        Restaurant <%= name %><br>
                        <%= list.people %> people<br>
                        Position: <%= pos %> <br>
                        <%= link_to 'Cancel', list, controller: 'waitlists', action: 'destroy',method: :delete%>
                      </div>
                    </div>
                  </a>
                </div>
            <% end %>
          <%else %>
            <div class="alert alert-danger">
              You are not waitlisted to any restaurant.
            </div>
          <%end %>

          <div class="col-xs-12 col-sm-6 col-md-6 col-lg">
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/waitlists/edit.html.erb
<h1>Editing Waitlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @waitlist %> |
<%= link_to 'Back', waitlists_path %>

app/views/waitlists/new.html.erb
<body class="signup">
<main>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4">
                <h1>New Waitlist</h1>
                    <% if flash[:error] %>
                      <div class="error"><%= flash[:error] %></div><br>
                    <% end %>
                    <%= form_for @waitlist do |f| %>
                    <p>
                        <%= f.label :people %>
                        <%= f.number_field :people, min: 1 %>
                    </p>
                    <p>   
                        <% if current_user.id.to_i != params[:rest_id].to_i %>
                            <%= f.hidden_field :name, :value => current_user.name %>
                        <% else %>
                            <%= f.label :name %>
                            <%= f.text_field :name, required: true %>
                        <% end %>
                    </p>
                        <%= f.hidden_field :rest_id, :value => params[:rest_id] %>
                    
                    
                     <div class="actions">
                    <!-- <button class="btn btn-bytlyn btn-max">Sign Up</button> -->
                    <%= f.submit "Create waitlist"%>
                    </div>
                    <% end %>
            </div>
        </div>
    </div>
</main>

app/views/waitlists/rest_index.html.erb
<body class="profile">
    <main class="">
        <div class="parallax-container">
            <div class="parallax"><img src="build/img/stock/cover-user.jpg" class="width-full" ></div>
            <div class="text">
                <h1> Restaurant List </h1>
            </div>
        </div>
        <div class="container">
            <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                <div class="wrapper-left">
                    <div class="side-pannel">
                        <a href="profile" class="tab chosen"><span class="fa fa-home"></span> Home</a>
                        <a href="favorite" class="tab"><span class="fa fa-star"></span> Favorite</a>
                        <a href="/waitlists"class="tab"><span class="fa fa-hourglass"></span> Waitlist</a>
                        <a href="delivery"class="tab"><span class="fa fa-rocket"></span> Delivery</a>
                        <a href="payment"class="tab"><span class="fa fa-credit-card"></span>Payment</a>
                        <a href="setting"class="tab"><span class="fa fa-cog"></span>Setting</a>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
                <div class="wrapper-right">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    
                        <p id="notice"><%= notice %></p>
                        
                        <div class="text-center">
                            <h1><%=current_user.name %>'s Waitlists</h1>
                            <table class="table table-striped">
                                <thead>
                                    <tr><th colspan="3"></th></tr>
                                </thead>
                                
                                <tbody >
                                    <% if not @lists.empty? %>
                                    <tr>
                                        <td>Name</th>
                                        <td># People</th>
                                        <td></th>
                                    </tr>
                                    
                                    <% @lists.each do |list| %>
                                    <tr>
                                        <td>

                                            <% name = User.where(id: list.cust_id).first.name %>
                                            <%= list.name %>
                                        </td>
                                        <td>
                                            <%= list.people %>
                                        </td>
                                        <td>
                                            <!-- <button class="btn btn-red">Delete</button>
                                            <%= link_to 'Delete', list, controller: 'waitlists', action: 'destroy',method: :delete%> -->
                                            <button class="btn btn-red"><%= link_to 'Delete', list, controller: 'waitlists', action: 'destroy',method: :delete%></button>
                                            
                                        </td>
                                    </tr>
                                    <% end %>
                                    <%else %>
                                    You have no current waitlist.
                                    <%end %>
                                </tbody>
                            </table>

                            <br><a class="btn btn-bytlyn" href="./waitlists_new?rest_id=<%= current_user.id %>"> New Waitlist</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    
    
    

app/views/waitlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @waitlist.id %>
</p>
<p>
  <strong>cust_id:</strong>
  <%= @waitlist.cust_id %>
</p>
 
<p>
  <strong>rest_id:</strong>
  <%= @waitlist.rest_id %>
</p>
<p>
  <strong>number_of_people:</strong>
  <%= @waitlist.people %>
</p>

<%= link_to 'Edit', edit_waitlist_path(@waitlist) %> |
<%= link_to 'Back', waitlists_path %>