config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :restaurants
  resources :customers
  resources :waitlists
  devise_scope :user do
     get "signup-user", to: "users/registrations#new_user"
     get "signup-restaurant", to: "users/registrations#new_rest"
     post "create-user", to: "users/registrations#create_user"
     post "create-restaurant", to: "users/registrations#create_rest"
     delete "destroy-user", to: "users/registrations#destroy"
     get "login", to: "users/sessions#new"
     get "sign_in", to: "users/sessions#new"
     post "sign_in", to: "users/sessions#create", as: "new_sign_in"
     get "logout", to: "users/sessions#destroy"
     get 'setting', to: "users/registrations#edit"
  end
  devise_for :users, controllers: {registrations: "users/registrations"}

  root 'dynamic_pages#home'

  get 'index.html' => 'dynamic_pages#index'
  get 'signup.html' => 'dynamic_pages#signup'
  get 'profile.html' => 'dynamic_pages#profile'
  get 'settings.html' => 'dynamic_pages#settings'
  get 'favorite.html' => 'dynamic_pages#favorite'
  get 'payment.html' => 'dynamic_pages#payment'
  get 'delivery.html' => 'dynamic_pages#delivery'

  get 'index' => 'dynamic_pages#index'
  get 'signup' => 'dynamic_pages#signup'
  get 'profile' => 'dynamic_pages#profile'
  get 'restaurants' => 'restaurants#index'
  get 'settings' => 'dynamic_pages#settings'
  get 'favorite' => 'dynamic_pages#favorite'
  get 'payment' => 'dynamic_pages#payment'
  get 'delivery' => 'dynamic_pages#delivery'
  get 'home' => 'dynamic_pages#home'
  get 'restaurant_page' => 'dynamic_pages#restaurant'

  get 'waitlists_new' => 'waitlists#new'
  post 'waitlists_new' => 'waitlists#create'

  get 'restaurant_new' => 'restaurants#new'
  get 'menus_new' => 'menus#new'
  get 'menus_edit' => 'menus#edit'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "300x300>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	def self.get_restaurant_menu(user_id)
        return Menu.where(rest_id: user_id).order(:created_at)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    if user_signed_in? and current_user.rest
      if Restaurant.find_by_user_id(current_user.id) != nil
        @lists = Menu.get_restaurant_menu(current_user.id)
        render 'rest_menu.html.erb' 
      else
        redirect_to restaurant_new_path
      end

      # else
      #   @waitlists = Waitlist.get_customer_waitlist(current_user.id)
      #   render 'cust_index.html.erb'   
    else
      redirect_to login_path
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    if user_signed_in? and current_user.rest
      @menu = Menu.new
    else
      redirect_to login_path
    end
  end

  # GET /menus/1/edit
  def edit
    if user_signed_in? and current_user.rest
      render 'new.html.erb'
    else
      redirect_to login_path
    end
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menus_path, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to menus_path, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      if params[:id] != nil
        @menu = Menu.find(params[:id])
      else
        redirect_to login_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:rest_id, :name, :description, :price, :avatar)
    end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  Rest ID: <%= f.text_field :rest_id %><br />
  Name : <%= f.text_field :name %><br />
  Description : <%= f.text_area :description %><br />
  Price : <%= f.text_area :price %><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Menus</h1>

<table>
  <thead>
    <tr>
      <th>Rest</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.rest_id %></td>
        <td><%= menu.name %></td>
        <td><%= menu.description %></td>
        <td><%= menu.price %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<body class="signup">
<main>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4">
              <% if flash[:error] %>
                      <div class="error"><%= flash[:error] %></div><br>
                    <% end %>
              <h1>New Menu</h1>
              fill this form below about details of your menu

              <%= form_for @menu do |f| %>
              <p>
                  <%= f.label :name %>
                  <%= f.text_field :name,  size: "24x6", required: true%>
              </p>
              <p>
                  <%= f.label :description %>
                  <%= f.text_field :description%>
              </p>
              <p>
                  <%= f.label :price %>
                  <%= f.text_field :price, required: true%>
              </p>
              <p>
                  <%= f.label :picture %>
                  <%= f.file_field :avatar %>
              </p>
	              <%= f.hidden_field :rest_id, :value => current_user.id %>
                  <%= f.submit "Create menu" %>
              <% end %>


              </div>
        </div>
    </div>
</main>

app/views/menus/rest_menu.html.erb
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"> -->
<body class="signup">
<main>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4">                    
    <!-- <p id="notice"><%= notice %></p> -->
                <div class="text-center">
                    <h1><%=current_user.name %>'s Menus</h1>
                    <table class="table table-striped">
                        <thead>
                            <tr><th colspan="3"></th></tr>
                        </thead>
                        
                        <tbody >
                            <% if not @lists.empty? %>
                            <tr>
                                <td>Picture</th>
                                <td>Name</th>
                                <td>Description</th>
                                <td>Price</th>
                                <td></th>
                                <td></th>
                            </tr>
                            
                            <% @lists.each do |list| %>
                            <tr>
                                <td>
                                    <%= image_tag(list.avatar.url(:thumb), :width => '50', :height => '50')%>
                                </td>
                                <td>
                                    <!--% name = User.where(id: list.cust_id).first.name %> -->
                                    <%= list.name %>
                                </td>
                                <td>
                                    <%= list.description %>
                                </td>
                                <td>
                                    <%= list.price %>
                                </td>
                                <td>
                                    <!-- <button class="btn btn-red">Delete</button>
                                    <%= link_to 'Delete', list, controller: 'menus', action: 'destroy',method: :delete%> -->
                                    <button class="btn btn-red"><%= link_to 'Delete', list, controller: 'menus', action: 'destroy',method: :delete%></button>
                                </td>
                                <td>
                                    <!-- <button class="btn btn-red">Delete</button>
                                    <%= link_to 'Delete', list, controller: 'menus', action: 'destroy',method: :delete%> -->
                                    <a class="btn btn-red" href="./menus_edit?id=<%= list.id %>"%>Edit</a>
                                </td>
                            </tr>
                            <% end %>
                            <%else %>
                            You have no menu.
                            <%end %>
                        </tbody>
                    </table>

                    <br><a class="btn btn-bytlyn" href="./menus_new"> New Menu</a><br>
                </div>
            </div>
        </div>
    </div>
</body>
<!-- </div> -->

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rest:</strong>
  <%= @menu.rest_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>