config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :restaurants
  resources :customers
  resources :waitlists
  devise_scope :user do
     get "signup-user", to: "users/registrations#new_user"
     get "signup-restaurant", to: "users/registrations#new_rest"
     post "create-user", to: "users/registrations#create_user"
     post "create-restaurant", to: "users/registrations#create_rest"
     delete "destroy-user", to: "users/registrations#destroy"
     get "login", to: "users/sessions#new"
     get "sign_in", to: "users/sessions#new"
     post "sign_in", to: "users/sessions#create", as: "new_sign_in"
     get "logout", to: "users/sessions#destroy"
     get 'setting', to: "users/registrations#edit"
  end
  devise_for :users, controllers: {registrations: "users/registrations"}

  root 'dynamic_pages#home'

  get 'index.html' => 'dynamic_pages#index'
  get 'signup.html' => 'dynamic_pages#signup'
  get 'profile.html' => 'dynamic_pages#profile'
  get 'settings.html' => 'dynamic_pages#settings'
  get 'favorite.html' => 'dynamic_pages#favorite'
  get 'payment.html' => 'dynamic_pages#payment'
  get 'delivery.html' => 'dynamic_pages#delivery'

  get 'index' => 'dynamic_pages#index'
  get 'signup' => 'dynamic_pages#signup'
  get 'profile' => 'dynamic_pages#profile'
  get 'restaurants' => 'restaurants#index'
  get 'settings' => 'dynamic_pages#settings'
  get 'favorite' => 'dynamic_pages#favorite'
  get 'payment' => 'dynamic_pages#payment'
  get 'delivery' => 'dynamic_pages#delivery'
  get 'home' => 'dynamic_pages#home'
  get 'restaurant_page' => 'dynamic_pages#restaurant'

  get 'waitlists_new' => 'waitlists#new'
  post 'waitlists_new' => 'waitlists#create'

  get 'restaurant_new' => 'restaurants#new'
  get 'menus_new' => 'menus#new'
  get 'menus_edit' => 'menus#edit'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :user
	has_many :waitlist

    
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @users = User.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      # params[:customer]
      params.require(:customer).permit(:phone_number, :user_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customers</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Phone_number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.user_id %></td>
        <td><%= User.find_by_id(customer.user_id).name %></td>
        <td><%= customer.phone_number%></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>email</th>
      <th colspan="3"></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= form_for @customer do |f| %>
<p>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
</p>
	<%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "Create customer" %>
<% end %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>