config/routes.rb
Rails.application.routes.draw do
  resources :menus
  resources :restaurants
  resources :customers
  resources :waitlists
  devise_scope :user do
     get "signup-user", to: "users/registrations#new_user"
     get "signup-restaurant", to: "users/registrations#new_rest"
     post "create-user", to: "users/registrations#create_user"
     post "create-restaurant", to: "users/registrations#create_rest"
     delete "destroy-user", to: "users/registrations#destroy"
     get "login", to: "users/sessions#new"
     get "sign_in", to: "users/sessions#new"
     post "sign_in", to: "users/sessions#create", as: "new_sign_in"
     get "logout", to: "users/sessions#destroy"
     get 'setting', to: "users/registrations#edit"
  end
  devise_for :users, controllers: {registrations: "users/registrations"}

  root 'dynamic_pages#home'

  get 'index.html' => 'dynamic_pages#index'
  get 'signup.html' => 'dynamic_pages#signup'
  get 'profile.html' => 'dynamic_pages#profile'
  get 'settings.html' => 'dynamic_pages#settings'
  get 'favorite.html' => 'dynamic_pages#favorite'
  get 'payment.html' => 'dynamic_pages#payment'
  get 'delivery.html' => 'dynamic_pages#delivery'

  get 'index' => 'dynamic_pages#index'
  get 'signup' => 'dynamic_pages#signup'
  get 'profile' => 'dynamic_pages#profile'
  get 'restaurants' => 'restaurants#index'
  get 'settings' => 'dynamic_pages#settings'
  get 'favorite' => 'dynamic_pages#favorite'
  get 'payment' => 'dynamic_pages#payment'
  get 'delivery' => 'dynamic_pages#delivery'
  get 'home' => 'dynamic_pages#home'
  get 'restaurant_page' => 'dynamic_pages#restaurant'

  get 'waitlists_new' => 'waitlists#new'
  post 'waitlists_new' => 'waitlists#create'

  get 'restaurant_new' => 'restaurants#new'
  get 'menus_new' => 'menus#new'
  get 'menus_edit' => 'menus#edit'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    validates :user_id, uniqueness: true
	belongs_to :user
	has_many :waitlist
    has_many :hours, :foreign_key => 'rest_id', :primary_key => 'user_id'
    has_many :menu, :foreign_key => 'rest_id'
    # validate :has_seven_hours
    accepts_nested_attributes_for :hours, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

    # def has_seven_hours
    #     errors.add(:hours, "hours not 7") if hours.size != 7
    # end

    
    def self.search(search)
        # todo:
        # search all column
        # search each word: http://stackoverflow.com/questions/6337381/search-on-multiple-keywords-in-a-single-search-text-field-rails
        # search by relevance
        # autocomplete: https://rubygems.org/gems/autocomplete/versions/1.0.2
        # advance: https://www.youtube.com/watch?v=eUtUquKc2qQ
        # pg full text search: https://www.youtube.com/watch?v=pfZw6yErsX0
        
        # gem choice :
        # textacular
        
        # find(:all, :conditions => [(['name LIKE ?'] * search_length).join(' OR ')] + search.split.map { |name| "%#{name}%" })
        
        
        if search
                find(:all, :order => "created_at DESC", :conditions => ['lower(address) LIKE ?', "%#{search}%"])
        else
                find(:all, :order => "created_at DESC")
        end
    end


end

app/controllers/restaurants_controller.rb
require "net/http"
require "uri"
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  # GET /restaurants
  # GET /restaurants.json
  def index
      # todo:
      # search each word: http://stackoverflow.com/questions/6337381/search-on-multiple-keywords-in-a-single-search-text-field-rails
      # search by relevance
      # autocomplete: https://rubygems.org/gems/autocomplete/versions/1.0.2
      # advance: https://www.youtube.com/watch?v=eUtUquKc2qQ
      # pg full text search: https://www.youtube.com/watch?v=pfZw6yErsX0
      
      # gem choice :
      # textacular
      @key = search_params[:key].present? ? search_params[:key] : ""
      @checkprice = search_params[:checkprice].present? ? search_params[:checkprice] : "false"
      @price = search_params[:price].present? ? search_params[:price] : "1"
      @checkrating = search_params[:checkrating].present? ? search_params[:checkrating] : "false"
      @rating = search_params[:rating].present? ? search_params[:rating] : "1"
      @category = search_params[:category].present? ? search_params[:category] : ""

      @restaurants = Restaurant.all
      
      # if has key to search for
      @restaurants = Restaurant.joins(:user).where("lower(name) LIKE ? OR lower(description) LIKE ? OR lower(rest_type) LIKE ? OR lower(city) LIKE ?", "%#{search_params[:key].downcase}%", "%#{search_params[:key].downcase}%", "%#{search_params[:key].downcase}%", "%#{search_params[:key].downcase}%") if search_params[:key].present?
      
      # if categories field is present
      @restaurants = @restaurants.where("lower(rest_type) LIKE ?","%#{search_params[:categories].downcase}%") if search_params[:categories].present?
      # if rating field is present
      @restaurants = @restaurants.where("rating = ?","#{search_params[:rating].downcase}") if search_params[:checkrating]
      # if price field is present
      @restaurants = @restaurants.where("price = ?","#{search_params[:price].downcase}") if search_params[:checkprice]
      # search by open now (day and time)
      @restaurants = @restaurants.joins(:hours).where("day_id = ? AND open <= ? AND close > ?","#{search_params[:day].downcase}","#{search_params[:time].downcase}","#{search_params[:time].downcase}") if search_params[:day].present? and search_params[:time].present?
      # search by location :http://www.scribd.com/doc/2569355/Geo-Distance-Search-with-MySQL
      # search by open hour
      
      @users = User.all
  end

#note for search
#      @restaurants = Restaurant.find_by address: search_params[:key]
# or .where("address = ? OR hours = ?", search_params[:key], search_params[:key])



  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    if user_signed_in?
      if current_user.rest && Restaurant.find_by_user_id(current_user.id) == nil
        @restaurant = Restaurant.new
        7.times {@restaurant.hours.build}
      else
        redirect_to profile_path, notice: 'Restricted Path'
      end
    else
      redirect_to signed_in_path, notice: 'Restricted Path'
    end
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    # render text: restaurant_params
    url = "http://api.zippopotam.us/us/" + restaurant_params[:zip]
    uri = URI.parse(url)
    response = Net::HTTP.get_response(uri)
    if response.body == nil or response.body.empty? or response.body == '{}'
      flash[:error] = "restaurant zip code not valid"
      redirect_to restaurant_new_path
      return
    else 
      response = JSON.parse(response.body)
      place = response['places']
      a = {}
      a[:lat] = place[0]['latitude']
      params[:restaurant][:lat] = place[0]['latitude']
      params[:restaurant][:lon] = place[0]['longitude']
    end

    @restaurant = Restaurant.new(restaurant_params)
    hours = restaurant_params[:hours_attributes]
    @hour = []
    hours.each  do |k, v|
      v[:day_id] = k.to_i + 1
      v[:rest_id] = restaurant_params[:user_id]
      @hour << Hour.new(v)
    end

    
    @hour.each do |h|
      if !h.valid? 
        flash[:error] = "Opening Hours Not Valid. Either both open and close hour should be empty or closing hour >= opening hour"
        redirect_to restaurant_new_path
        return
      end
    end
    if !@restaurant.valid?
      flash[:error] = "restaurant details not valid"
      redirect_to restaurant_new_path
      return
    end

    @hour.each do |h|
      h.save
    end

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to profile_path, notice: 'Restaurant was successfully created.'}
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
    
    def hours_params
      params.require(:hours).permit(:close, :hour)
    end
    
    def search_params
        params.permit(:key,:categories,:rating,:price,:day,:time,:checkprice,:checkrating)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      # params[:restaurant]
      params.require(:restaurant).permit(:address, :city, :zip, :hours, :user_id, :rest_type, :price, :description, :lon, :lat,hours_attributes: [:day_id, :open, :close, :rest_id])
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  User ID: <%= f.text_field :user_id %><br />
  Address : <%= f.text_field :address %><br />
  Hours : <%= f.text_area :hours %><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<body class="profile">
<main class="">
    <div class="parallax-container">
        <div class="parallax"><img src="build/img/stock/cover-user.jpg" class="width-full" ></div>
        <div class="text">
            <h1> Restaurant List </h1>
        </div>
    </div>
    <div class="container">
    <% if user_signed_in? && (!current_user.rest || Restaurant.find_by_user_id(current_user.id) != nil) %>
        <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
            <div class="wrapper-left">
                <div class="side-pannel">
                    <a href="profile" class="tab chosen"><span class="fa fa-home"></span> Home</a>
                    <a href="favorite" class="tab"><span class="fa fa-star"></span> Favorite</a>
                    <a href="/waitlists"class="tab"><span class="fa fa-hourglass"></span> Waitlist</a>
                    <a href="delivery"class="tab"><span class="fa fa-rocket"></span> Delivery</a>
                    <a href="payment"class="tab"><span class="fa fa-credit-card"></span>Payment</a>
                    <a href="setting"class="tab"><span class="fa fa-cog"></span>Setting</a>
                </div>
            </div>
        </div>
    <% end %>
        <% if user_signed_in? %>
        <div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
        <% else %>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <% end %>
            <div class="wrapper-right" style="padding:20px;">
                <div>
                    <%= form_tag("/restaurants", method: "get", :id => "myform")do %>
                        <p>
                            <label for="input">Search</label>
                            <input id="input" style="margin-left:auto;margin-right:auto;margin-top:0px;margin-bottom:5px;color:black;font-size:30px;" type="text" name="key" value="<%=@key%>"onkeydown="if (event.keyCode == 13 && $('#myform #input').val().length != 0) { document.myform.submit(); return false; }"></input>
                        </p>
                        <p>
                            <label for="price">Price</label>
                            <% if @checkprice == "true" %>
                                <input type="checkbox" name="checkprice" value="true" checked>
                            <% else %>
                                <input type="checkbox" name="checkprice" value="true">
                            <% end %>
                            
                            <input type="range" name="price" min="1" max="4" value="<%=@price%>" style="width:300px;"/>
                        </p>
                        <p>
                            <label for="rating">Rating</label>
                            <% if @checkrating == "true" %>
                                <input type="checkbox" name="checkrating" value="true" checked>
                            <% else %>
                                <input type="checkbox" name="checkrating" value="true">
                            <% end %>
                            
                            <input type="range" name="rating" min="1" max="5" value="<%=@rating%>" style="width:300px;"/>
                        </p>
                        <p>
                        <label for="category">Category</label>
                        <select name="category" id="category" value="<%=@category%>">
                            <option value="">None</option>
                            <option value="American">American</option>
                            <option value="Italian">Italian</option>
                            <option value="French">French</option>
                            <option value="Japanese">Japanese</option>
                            <option value="Chinese">Chinese</option>
                            <option value="Asian">Asian</option>
                        </select>
                        </p>
                        <input type="submit" style="margin-bottom:40px;">
                    <% end %>
                    
                </div>
                <% if !@restaurants.blank?%>
                    <% @restaurants.each do |restaurant| %>
                        <% if @users.find_by_id(restaurant.user_id) != nil %>
                        <div class="col-md-6">
                            
                                <div class="panel panel-default restaurant-panel">
                                    <a href = './restaurant_page?rest_id=<%= restaurant.user_id %>' style="display:inline-block;">
                                    <div class="panel-heading"><%= @users.find_by_id(restaurant.user_id).name %></div>
                                    </a>
                                    <div class="panel-body">
                                        <div class="col-md-3">
                                            <%= image_tag(@users.find_by_id(restaurant.user_id).avatar.url(:thumb), :width => '120', :height => '120')%>
                                        </div>
                                        <div class="col-md-9">
                                            <ul class="pull-right">
                                                <li>price:<%=restaurant.price%></li>
                                                <li>rating:<%=restaurant.rating%>
                                                    <img src="build/img/stock/star.png" alt="Restaurant Logo" width="30" height="30">
                                                </li>
                                                <li>Open now!</li>
                                                <li><% if (user_signed_in? && !current_user.rest) %>
                                                    <a class="btn btn-warning" href="./waitlists_new?rest_id=<%= restaurant.user_id %>">Waitlist</a>
                                                    <% elsif !user_signed_in? %>
                                                        <a class="btn btn-warning" href="./login">Waitlist</a>
                                                    <% end %>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                
                                </div>
                            

                        </div>
                        <%end%>
                    <% end %> <!--end of for loop-->
                <% else %>
                    <h2> Search </h2>
                    <p>Can't find anything</p>
                    <p>Suggestions</p>
                    <ul style="list-style-type: circle;">
                        <li>Make sure all words are spelled correctly
                        <li>Try different keywords
                    </ul>

                <% end %>
            </div>
        </div>
    </div>
</main>

app/views/restaurants/new.html.erb
<body class="signup">
<main>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4 col-lg-offset-4 col-lg-4">
              <% if flash[:error] %>
                      <div class="error"><%= flash[:error] %></div><br>
                    <% end %>
              <h1>New Restaurant</h1>
              fill this form below about details of your restaurant

              <%= form_for @restaurant do |f| %>
              <p>
                  <%= f.label :description %>
                  <%= f.text_field :description,  size: "24x6", required: true%>
              </p>
              <p>
                  <%= f.label :price %>
                  <%= f.select :price, options_for_select([['$', 1], ['$$', 2],['$$$', 3], ['$$$$', 4] ], required: true) %>
              </p>
              <p>
                  <%= f.label :address %>
                  <%= f.text_field :address, required: true %>
              </p>
              <p>
                  <%= f.label :city %>
                  <%= f.text_field :city, required: true %>
              </p>
              <p>
                  <%= f.label :zip_code %>
                  <%= f.text_field :zip, required: true %>
              </p>
              <p>
                  <%= f.label :restaurant_type %>
                  <%= f.select :rest_type, options_for_select(['American', 'Italian', 'French', 'Japanese', 'Chinese', 'Asian']), required: true %>
              </p>
              <h2> Opening Hours </h2><br>
              <% days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %>
              <% i = 0 %>
              <p>
                  <%= f.fields_for :hours do |builder| %>
                      <p>
                        <%=days[i]%> <br>
                        <%=builder.label :open %>
                        <%=builder.time_field :open %>
                        <%=builder.label :close %>
                        <%=builder.time_field :close %>
                        <%= builder.hidden_field :rest_id, :value => current_user.id %>
                        <%= builder.hidden_field :day_id, :value =>  1%>
                        <%i=i+1%>
                    </p>
                  <% end %>
                  
              </p>

              	<%= f.hidden_field :user_id, :value => current_user.id %>
                  <%= f.submit "Create restaurant" %>
              <% end %>


              </div>
        </div>
    </div>
</main>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', profile_path %>